# Generated by Django 2.1.5 on 2019-02-13 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=10000, verbose_name='Values')),
            ],
            options={
                'verbose_name': 'Answers',
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_keyword', models.CharField(max_length=1000, verbose_name='Keyword')),
            ],
            options={
                'verbose_name': 'Questions',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='question_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lifequotesbot.Questions', verbose_name='Key'),
        ),
    ]
