# Generated by Django 2.1.5 on 2019-02-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifequotesbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_user', models.CharField(max_length=200, verbose_name='Recipients FB name')),
                ('message', models.CharField(max_length=200, verbose_name='Message Received')),
                ('response', models.CharField(max_length=200, verbose_name='Recipients FB name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat Records',
                'verbose_name_plural': 'Chat Records',
            },
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'verbose_name': 'Questions Or Keywords', 'verbose_name_plural': 'Questions Or Keywords'},
        ),
    ]
