# Generated by Django 2.2.4 on 2019-08-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifequotesbot', '0002_auto_20190213_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoRecordFoundResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsetext', models.CharField(max_length=200, verbose_name='Response Text')),
            ],
            options={
                'verbose_name': 'No Record Found Response',
                'verbose_name_plural': 'No Record Found Responses',
            },
        ),
    ]
